name: Deploy to lambda

on:
  push:
    branches:
      - master

jobs:
  deploy_source:
    name: Deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Default deploy
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Configure AWS credentials    
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
      - name: Install boto 3
        run: |
          pip install boto3
      - name: Install moto
        run: |
          pip install moto 

          function_name: Visitor-Count
          source: './lambda/count.py'